version: 2

references:
  build-steps: &build-steps
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
    - run: cp config.example.js src/config.js
    - run: npm install
    - run: npm run build
    - save_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
        paths:
          - node_modules

jobs:
  build-node8:
    docker:
      - image: circleci/node:8
    steps: *build-steps
  build-node10:
    docker:
      - image: circleci/node:10
    steps: *build-steps
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build-node8
      - build-node10
      - lint
