version: 2.1

references:
  test-steps: &test-steps
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
    - run: cp example.env .env
    - run: npm install
    - run: npm test
    - run: npm run build
    - save_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
        paths:
          - node_modules

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
            echo "CIRCLE_BRANCH: $CIRCLE_BRANCH"
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi
            case "$CIRCLE_BRANCH" in
              "dependabot/"*)
                echo "Nothing to do for dependabot PRs, so marking this step successful"
                circleci step halt
                ;;
            esac

jobs:
  test-node18:
    docker:
      - image: cimg/node:18.18
    steps: *test-steps
  test-node20:
    docker:
      - image: cimg/node:20.3
    steps: *test-steps
  lint:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

  prettier:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run: npm install --also=dev
      - run: npx prettier --check **/*.ts

  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              docker build \
                --no-cache \
                -t coredump/flamebot:latest \
                -t coredump/flamebot:master \
              .
            else
              docker build \
                --no-cache \
                -t coredump/flamebot:branch-${CIRCLE_BRANCH//\//-} \
              .
            fi
      - early_return_for_forked_pull_requests
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_API_KEY && \
            docker push coredump/flamebot

workflows:
  version: 2

  # Build on push
  push:
    jobs:
      - test-node18
      - test-node20
      - lint
      - prettier
      - build:
          requires:
            - test-node18
            - test-node20
            - lint
          context: Docker Hub coredumpuploader

  # Build every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: Docker Hub coredumpuploader
