version: 2

references:
  test-steps: &test-steps
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
    - run: cp example.env .env
    - run: npm install
    - run: npm test
    - run: npm run build
    - save_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
        paths:
          - node_modules

jobs:
  test-node8:
    docker:
      - image: circleci/node:8
    steps: *test-steps
  test-node10:
    docker:
      - image: circleci/node:10
    steps: *test-steps
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint
      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - test-node8
      - test-node10
      - lint
